services:
  db:
    container_name: postgresTutorial
    image: postgres
    environment:
      POSTGRES_USER: arashid
      POSTGRES_PASSWORD: password!
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: